export default {
	// ----- Server to Client -----
	NOTIFICATION_BROADCAST: 'NOTIFICATION_BROADCAST',

	// ----- Client to Server -----
	NOTIFICATION_CREATE: 'NOTIFICATION_CREATE',
	NOTIFICATION_READ: 'NOTIFICATION_READ',
	NOTIFICATION_DELETE: 'NOTIFICATION_DELETE',
}